apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: veleros.konveyor.openshift.io
spec:
  group: konveyor.openshift.io
  names:
    kind: Velero
    listKind: VeleroList
    plural: veleros
    singular: velero
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
