apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-sample
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
    restic:
      enable: true
  backupLocations:
    - name: foo
      velero:
        provider: aws
        default: true
        objectStorage:
          bucket: my-bucket-name
          prefix: velero
        config:
          region: us-east-1
          profile: "default"
        credential:
          name: cloud-credentials
          key: cloud
  volumeSnapshots:
  - velero:  
      provider: aws
      config:
        region: us-west-2
        profile: "default"
